{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4742a3b1-cd5b-4027-9d4c-eea67146196e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "MACE Stage Two Usage Example - Integration with CI Operator\n",
    "This example demonstrates how to use the new MACEEvolver class and CI operator.\n",
    "\"\"\"\n",
    "import numpy as np\n",
    "from typing import Dict, List\n",
    "from src.run_hyper_heuristic.run_hyper_heuristic import evaluate_all_heuristics\n",
    "from src.run_hyper_heuristic.MACEEvolver import MACEEvolver\n",
    "\n",
    "\n",
    "def main():\n",
    "    \"\"\"Main function.\"\"\"\n",
    "    \n",
    "    # Configuration\n",
    "    problem = \"cvrp\"\n",
    "    api_key = \"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\"\n",
    "    model = \"x-ai/grok-code-fast-1\"\n",
    "    \n",
    "    heuristic_dir = \"basic_heuristics\"\n",
    "    task_description_file = f\"src/problems/{problem}/task_description.txt\"\n",
    "    output_dir = f\"src/problems/{problem}/heuristics/basic_heuristics\"\n",
    "    test_data = \"test_data\"\n",
    "    result_dir = \"result\"\n",
    "    \n",
    "    population_size = 10\n",
    "    max_evaluations = 3\n",
    "    time_limit = 10 * 60\n",
    "    iterations_scale_factor = 1.0\n",
    "    \n",
    "    # Step 1: Evaluate initial heuristics (output from Stage One)\n",
    "    print(\"=\" * 80)\n",
    "    print(\"📋 Step 1: Evaluating Initial Heuristics\")\n",
    "    print(\"=\" * 80)\n",
    "    \n",
    "    initial_results_dict = evaluate_all_heuristics(\n",
    "        problem=problem,\n",
    "        heuristic_dir=heuristic_dir,\n",
    "        test_data=test_data,\n",
    "        iterations_scale_factor=iterations_scale_factor,\n",
    "        result_dir=result_dir,\n",
    "        save_to_file=True,\n",
    "        time_limit=time_limit\n",
    "    )\n",
    "    \n",
    "    print(\"\\nInitial evaluation results:\")\n",
    "    for h_name, scores in initial_results_dict.items():\n",
    "        avg = np.mean(scores)\n",
    "        print(f\"  {h_name}: avg={avg:.2f}, scores={scores}\")\n",
    "    \n",
    "    # Step 2: Run MACE Stage Two\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"📋 Step 2: Running MACE Stage Two\")\n",
    "    print(\"=\" * 80)\n",
    "    \n",
    "    mace = MACEEvolver(\n",
    "        problem=problem,\n",
    "        api_key=api_key,\n",
    "        heuristic_dir=heuristic_dir,\n",
    "        task_description_file=task_description_file,\n",
    "        output_dir=output_dir,\n",
    "        model=model,\n",
    "        population_size=population_size,\n",
    "        max_evaluations=max_evaluations,\n",
    "        time_limit=time_limit\n",
    "    )\n",
    "    \n",
    "    final_population = mace.run(initial_results_dict, time_limit)\n",
    "    \n",
    "    # Step 3: Output final results\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"📊 Final Results\")\n",
    "    print(\"=\" * 80)\n",
    "    \n",
    "    print(f\"🎯 Final heuristic set size: {len(final_population)}\")\n",
    "    print(f\"🏆 Final CPI: {mace.compute_cpi(final_population):.4f}\")\n",
    "    print(f\"📈 Total evaluations: {mace.evaluations}\")\n",
    "    \n",
    "    print(\"\\n📋 Final heuristic set:\")\n",
    "    for i, h in enumerate(final_population, 1):\n",
    "        print(f\"  {i}. {h['name']}\")\n",
    "        print(f\"     avg={h['avg_performance']:.2f}\")\n",
    "        print(f\"     scores={h['performance_vector']}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44a8608d-d99f-4257-8dfa-910c3efbc66d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
