{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "imports",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Checking required dependency files...\n",
      "\n",
      "✅ State Space (S) generated\n",
      "✅ Action Space (A) generated\n",
      "\n",
      "Note: Tool library can be generated without S and A, but quality may be lower\n",
      "Initializing LLM client...\n",
      "Creating Tool Library Builder...\n",
      "✅ Initialization complete!\n",
      "\n",
      "============================================================\n",
      "Starting tool library generation...\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Starting Tool Library Generation\n",
      "============================================================\n",
      "\n",
      "[Step 1/4] Analyzing problem and identifying tool categories...\n",
      "Chat dumped to output\\tsp\\generate_tool_library\\tool_categories.txt\n",
      "  Identified 4 tool categories:\n",
      "    1. Insertion_Position_Optimization\n",
      "    2. Lower_Bound_Estimation\n",
      "    3. Local_Search_Improvement\n",
      "    4. Solution_Gap_Analysis\n",
      "\n",
      "[Step 2/4] Generating tools for each category...\n",
      "  [1/4] Generating Insertion_Position_Optimization tools...\n",
      "Chat dumped to output\\tsp\\generate_tool_library\\tools_Insertion_Position_Optimization.txt\n",
      "  [2/4] Generating Lower_Bound_Estimation tools...\n",
      "Chat dumped to output\\tsp\\generate_tool_library\\tools_Lower_Bound_Estimation.txt\n",
      "  [3/4] Generating Local_Search_Improvement tools...\n",
      "Chat dumped to output\\tsp\\generate_tool_library\\tools_Local_Search_Improvement.txt\n",
      "  [4/4] Generating Solution_Gap_Analysis tools...\n",
      "Chat dumped to output\\tsp\\generate_tool_library\\tools_Solution_Gap_Analysis.txt\n",
      "\n",
      "[Step 3/4] Assembling tool library...\n",
      "Tool library temporarily saved to: output\\tsp\\generate_tool_library\\tool_library.py\n",
      "Tool documentation generated: output\\tsp\\generate_tool_library\\tool_library_documentation.txt\n",
      "\n",
      "============================================================\n",
      "✅ Tool library generation completed!\n",
      "Saved to: output\\tsp\\generate_tool_library\\tool_library.py\n",
      "============================================================\n",
      "\n",
      "\n",
      "✅ Tool library generation successful!\n",
      "📁 File location: output\\tsp\\generate_tool_library\\tool_library.py\n",
      "📄 Documentation location: output\\tsp\\generate_tool_library\\tool_library_documentation.txt\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "project_root = os.path.abspath('..')\n",
    "if project_root not in sys.path:\n",
    "    sys.path.insert(0, project_root)\n",
    "\n",
    "from src.pipeline.tool_library_builder import ToolLibraryBuilder\n",
    "from src.util.llm_client.get_llm_client import get_llm_client\n",
    "\n",
    "# Configuration\n",
    "problem = \"tsp\"\n",
    "smoke_test = False\n",
    "llm_config_file = os.path.join(\"output\", \"llm_config\", \"azure_gpt_4o.json\")\n",
    "max_try_times = 5\n",
    "\n",
    "# Check dependencies\n",
    "print(\"Checking required dependency files...\\n\")\n",
    "\n",
    "state_file = os.path.join(\"output\", problem, \"generate_problem_state\", \"problem_state.py\")\n",
    "if os.path.exists(state_file):\n",
    "    print(\"✅ State Space (S) generated\")\n",
    "else:\n",
    "    print(\"⚠️  State Space (S) not found\")\n",
    "    print(f\"   Recommend running: generate_problem_state.ipynb first\")\n",
    "\n",
    "action_file = os.path.join(\"output\", problem, \"generate_action_space\", \"action_space.py\")\n",
    "comp_file = os.path.join(\"src\", \"problems\", problem, \"components.py\")\n",
    "if os.path.exists(action_file) or os.path.exists(comp_file):\n",
    "    print(\"✅ Action Space (A) generated\")\n",
    "else:\n",
    "    print(\"⚠️  Action Space (A) not found\")\n",
    "    print(f\"   Recommend running: generate_action_space.ipynb first\")\n",
    "\n",
    "print(\"\\nNote: Tool library can be generated without S and A, but quality may be lower\")\n",
    "\n",
    "# Initialize\n",
    "prompt_dir = os.path.join(\"src\", \"problems\", \"base\", \"prompt\")\n",
    "output_dir = os.path.join(\"output\", problem, \"generate_tool_library\")\n",
    "os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "print(\"Initializing LLM client...\")\n",
    "llm_client = get_llm_client(llm_config_file, prompt_dir, output_dir)\n",
    "\n",
    "print(\"Creating Tool Library Builder...\")\n",
    "tool_builder = ToolLibraryBuilder(llm_client=llm_client, problem=problem)\n",
    "print(\"✅ Initialization complete!\")\n",
    "\n",
    "# Generate tool library\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"Starting tool library generation...\")\n",
    "print(\"=\"*60 + \"\\n\")\n",
    "\n",
    "result_file = tool_builder.generate_tool_library(\n",
    "    smoke_test=smoke_test,\n",
    "    max_try_times=max_try_times\n",
    ")\n",
    "\n",
    "if result_file:\n",
    "    print(f\"\\n✅ Tool library generation successful!\")\n",
    "    print(f\"📁 File location: {result_file}\")\n",
    "    print(f\"📄 Documentation location: {result_file.replace('.py', '_documentation.txt')}\")\n",
    "else:\n",
    "    print(f\"\\n❌ Tool library generation failed\")\n",
    "    print(f\"Please check log files in output directory: {output_dir}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4315c2e-e7df-44cc-a634-4850fe2c7ba2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
