{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "imports",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initializing LLM client...\n",
      "Creating Action Designer...\n",
      "✅ Initialization complete!\n",
      "\n",
      "============================================================\n",
      "Starting action space generation...\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Starting Action Space Generation\n",
      "============================================================\n",
      "\n",
      "[Step 1/3] Generating Constructive Actions...\n",
      "Chat dumped to output\\tsp\\generate_action_space\\constructive_actions.txt\n",
      "\n",
      "[Step 2/3] Generating Improvement Actions...\n",
      "Chat dumped to output\\tsp\\generate_action_space\\improvement_actions.txt\n",
      "\n",
      "[Step 3/3] Assembling and saving action space...\n",
      "Action space temporarily saved to: output\\tsp\\generate_action_space\\action_space.py\n",
      "\n",
      "=== Smoke Test Started ===\n",
      "  Testing constructive actions...\n",
      "    - Found action: AppendOperator\n",
      "    - Found action: InsertOperator\n",
      "  Testing improvement actions...\n",
      "    - Found action: SwapOperator\n",
      "    - Found action: TwoOptOperator\n",
      "    - Found action: ReverseOperator\n",
      "    - Found action: OrOptOperator\n",
      "✅ Smoke test passed!\n",
      "\n",
      "============================================================\n",
      "✅ Action space generation completed!\n",
      "Saved to: output\\tsp\\generate_action_space\\action_space.py\n",
      "============================================================\n",
      "\n",
      "\n",
      "✅ Action space generation successful!\n",
      "📁 File location: output\\tsp\\generate_action_space\\action_space.py\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "project_root = os.path.abspath('..')\n",
    "if project_root not in sys.path:\n",
    "    sys.path.insert(0, project_root)\n",
    "\n",
    "from src.pipeline.action_designer import ActionDesigner\n",
    "from src.util.llm_client.get_llm_client import get_llm_client\n",
    "\n",
    "# Configuration\n",
    "problem = \"tsp\"\n",
    "smoke_test = True\n",
    "llm_config_file = os.path.join(\"output\", \"llm_config\", \"azure_gpt_4o.json\")\n",
    "max_try_times = 5\n",
    "\n",
    "# Initialize directories\n",
    "prompt_dir = os.path.join(\"src\", \"problems\", \"base\", \"prompt\")\n",
    "output_dir = os.path.join(\"output\", problem, \"generate_action_space\")\n",
    "os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "# Create LLM client\n",
    "print(\"Initializing LLM client...\")\n",
    "llm_client = get_llm_client(llm_config_file, prompt_dir, output_dir)\n",
    "\n",
    "# Create Action Designer\n",
    "print(\"Creating Action Designer...\")\n",
    "action_designer = ActionDesigner(llm_client=llm_client, problem=problem)\n",
    "print(\"✅ Initialization complete!\")\n",
    "\n",
    "# Generate action space\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"Starting action space generation...\")\n",
    "print(\"=\"*60 + \"\\n\")\n",
    "\n",
    "result_file = action_designer.generate_action_space(\n",
    "    smoke_test=smoke_test,\n",
    "    max_try_times=max_try_times\n",
    ")\n",
    "\n",
    "if result_file:\n",
    "    print(f\"\\n✅ Action space generation successful!\")\n",
    "    print(f\"📁 File location: {result_file}\")\n",
    "else:\n",
    "    print(f\"\\n❌ Action space generation failed\")\n",
    "    print(f\"Please check log files in output directory: {output_dir}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "271134fe-1bc9-4250-b6c1-ddb2cefeb79d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
